language: generic 
sudo: required 
services:
  - docker

before_install: 
  - docker build -t wendyharris/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wendyharris/react-test npm test 

after_success:
  - docker build -t wendyharris/multi-client ./client
  - docker build -t wendyharris/multi-nginx ./nginx 
  - docker build -t wendyharris/multi-server ./server
  - docker build -t wendyharris/multi-worker ./worker 
  # Log in to the Docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push wendyharris/multi-client
  - docker push wendyharris/multi-nginx
  - docker push wendyharris/multi-server
  - docker push wendyharris/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-160539809319'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY